// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_hzOu8FdBRJHCuSaeJihg7mFR8WX7kRs',
    appId: '1:884339429918:android:6d738aceb1ac0e7ae7140f',
    messagingSenderId: '884339429918',
    projectId: 'edukid-60f55',
    storageBucket: 'edukid-60f55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8uTwlHkS8EhFxNfTbpfS960HjHGEiEU',
    appId: '1:884339429918:ios:ccfd3bcbe495c848e7140f',
    messagingSenderId: '884339429918',
    projectId: 'edukid-60f55',
    storageBucket: 'edukid-60f55.appspot.com',
    androidClientId: '884339429918-7jhg2gnlt7hl9atn0mj52mo109k4o77u.apps.googleusercontent.com',
    iosClientId: '884339429918-q2cjqog3178p9t7rau272lkc7uom9kq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.edukid',
  );
}
